### ISSUE TITLE
Invalid syntax is found in these scripts "Erosion.py & Dilation.py"

### ISSUE THREAD

**Issue by truongsatthu** [TANAKA-Makoto/image_filter_test#1]
The issue is happened when executing by the following the steps: 
1. I created a ~/img folder and put image named "test.png" as it said.
2. Ran some commands but I got errors, e.g., "./Erosion.py '~/img/test.png' 3 --append_dst '~/img/'".
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
The syntax of these scripts is checked  by "python -m py_compile python -m py_compile Erosion.py Dilation.py". It is shown in the attached photo.
![img_filter_errors](https://user-images.githubusercontent.com/35186419/124886603-5e877900-e00f-11eb-915e-d3895c2bb1c3.png)

**Comment by TANAKA-Makoto** [comment]
@truongsatthu pleas tell me your python version with `python3 --version`

**Comment by TANAKA-Makoto** [comment]
this script use " formatted string literal"
https://www.python.org/dev/peps/pep-0498
it is supported from v3.6

**Comment by truongsatthu** [comment]
> python3 --version
Thank you for you quick respond!
==> Python 3.5.2 is the output. It seems the problem is found. Should I update my python version then?

**Comment by truongsatthu** [comment]
> this script use " formatted string literal"
> https://www.python.org/dev/peps/pep-0498
> it is supported from v3.6

YES. Thank you for the info. It works well after I update to python 3.6.

**Comment by truongsatthu** [comment]
***Note:
After installing the new python (3.6), it may have a minor issue while executing the scripts which is caused by $PYTHONPATH.
1. check it by #  echo $PYTHONPATH
2. If it is not related to ~/python3.6/dist-packages, put the command # export PYTHONPATH="/usr/local/lib/python3.6/dist-packages:$PYTHONPATH" to ~/.bashrc
